source "https://rubygems.org"
git_source(:github){|repo| "https://github.com/#{repo}.git"}

gem "bcrypt"
gem "bootsnap", ">= 1.4.2", require: false
gem "config"
gem "dotenv-rails", require: "dotenv/rails-now"
gem "dry-logic", "1.0.6"
gem "dry-schema", "1.5.2"
gem "dry-validation", "1.5.3"
gem "faker"
gem "grape"
gem "grape-entity"
gem "grape_on_rails_routes"
gem "jwt", "2.2.1"
gem "mysql2", ">= 0.4.4"
gem "puma", "~> 4.1"
gem "rack-cors"
gem "rails", "~> 6.0.3", ">= 6.0.3.2"
gem "rails-i18n"
gem "spring", "2.1.0"

group :development do
  gem "listen", "~> 3.2"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :development do
  gem "rails_best_practices"
  gem "rubocop", require: false
  gem "rubocop-rails", "~> 2.3.2", require: false
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "database_cleaner-active_record"
  gem "factory_bot_rails"
  gem "hirb"
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "simplecov", require: false
end

group :test do
  gem "capybara", ">= 2.15"
  gem "selenium-webdriver"
  gem "webdrivers"
end
